### ISSUE TITLE
Creating the Azure SQL Database

### ISSUE THREAD

**Issue by rajeshagadi-xx** [dxcamps/MicrosoftIntelIoTCamp#1]
Step 16:  The Wrokspace settings show vscode.mssql that needs to be corrected manually with mssql.
![vscode-mssql](https://cloud.githubusercontent.com/assets/17166696/22956570/bca7f084-f2d7-11e6-8c03-cc7fa6221731.png)

**Comment by BretStateham** [comment]
This is resoved in the later releases, and the docs have been updated to reflect the use of the mssql plugin.
