### ISSUE TITLE
HOLs readme powerbi-cli on macOS

### ISSUE THREAD

**Issue by Pindar** [dxcamps/MicrosoftIntelIoTCamp#2]
It might be cool to have a reference to [this issue](https://github.com/Microsoft/PowerBI-Cli/issues/5#issuecomment-251419579) with powerbi-cli on macOS when you face this error message:
```
powerbi-config(1) does not exist, try --help
```

see
https://github.com/Microsoft/PowerBI-Cli/issues/5#issuecomment-251419579

**Comment by BretStateham** [comment]
Done
