### ISSUE TITLE
HOLs readme: using powerbi update-connection

### ISSUE THREAD

**Issue by Pindar** [dxcamps/MicrosoftIntelIoTCamp#3]
if you run into `parameters[valueElement] must be of type object.` you should take a look at

https://github.com/Microsoft/PowerBI-Cli/issues/48

**Comment by BretStateham** [comment]
Not sure I want to link to that in the docs, because it doesn't really show a solution.

**Comment by Pindar** [comment]
@BretStateham I wouldn't do it neither but I thought it makes it easier to find a starting point. Furthermore it makes clear that the "user" has done everything right. But feel free to close it.

**Comment by BretStateham** [comment]
Did you encounter the error?  If so, were you able to get past it?

**Comment by Pindar** [comment]
I encountered the error and had no way to workaround. I hope there will be a fix soonish since the linked issue is just a few days old.

**Comment by BretStateham** [comment]
What OS are you running on, Mac OSX?  I just tested it with powerbi-cli 1.0.6 on my Windows 10 machine and it worked.  

If you have access to a Windows Machine, you could do it from there to continue.

**Comment by BretStateham** [comment]
I added a note right before the powerbi-cli install step that users on Non-Windows OSs may have issues with the CLI, and that if possible for now they should run those statements from a Windows machine.  I'm keeping this issue open until the powerbi-cli issues are resolved, at which point I can clean these docs back up.

**Comment by Pindar** [comment]
I'm using macOS 10.12.2 and unfortunately I have no windows machine (VM would be possible but it's too much effort to set everything up for a trial session and I missed only the very last few steps).
Thank you very much for assisting! I'm very impressed how fast the response came!

**Comment by BretStateham** [comment]
This should have been corrected by the power-bi cli team.  I'm closing it out here as well. [/PowerBI-Cli/issues/48](https://github.com/Microsoft/PowerBI-Cli/issues/48)

**Comment by BretStateham** [comment]
This should have been corrected by the power-bi cli team. I'm closing it out here as well. /PowerBI-Cli/issues/48
