### ISSUE TITLE
Can't run bower install in web app, wrong PowerBi version

### ISSUE THREAD

**Issue by buzzfrog** [dxcamps/MicrosoftIntelIoTCamp#5]
Hi
I had problem publish the web app. when it runs bower install it doesn't find powerbi-client with that version number. I updated to 2.3.0 and it works.
/dag

**Comment by BretStateham** [comment]
Thanks, I had to peg the versions previously because I was having issues.  I'll review it again and update.

**Comment by BretStateham** [comment]
Power BI Embedded has changed significantly and is no longer covered in this lab.  If it stabilizes, we can look at adding it back in in the future.   The latest release should work all the way through without Power BI. The place holder chart still appears in the web app and may be replaced with something else in the future, but for now it will remain as is.
